name: interactive_webview
description: Plugin that allow Flutter to communicate with a native WebView.
version: 1.0.0
homepage: https://github.com/duyduong/interactive_webview

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nover.interactivewebview
        pluginClass: InteractiveWebviewPlugin
      ios:
        pluginClass: InteractiveWebviewPlugin
